# Generated by Django 5.2.15 on 2026-08-03 00:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('device_name', models.CharField(default='NeuralOps Desktop', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('session_expires_at', models.DateTimeField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'device_sessions',
            },
        ),
        migrations.CreateModel(
            name='Right',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text="Stable identifier, e.g. 'project.create'. Referenced by code everywhere, never by id.", max_length=100, unique=True)),
                ('object_type', models.CharField(choices=[('project', 'Project'), ('channel', 'Channel'), ('topic', 'Chat Topic'), ('session', 'Chat Session'), ('persona', 'Persona'), ('agent', 'AI Agent'), ('mcp_server', 'MCP Server'), ('ai_model', 'AI Model'), ('company', 'Company')], max_length=20)),
                ('scope', models.CharField(choices=[('company', 'Company'), ('project', 'Project'), ('topic', 'Topic')], help_text='Narrowest scope level this right can be granted at. See ScopeType docstring.', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'authn_right',
                'ordering': ['object_type', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text="The philosophy — why this role exists and what it's meant to represent.")),
                ('scope', models.CharField(choices=[('company', 'Company'), ('project', 'Project'), ('topic', 'Topic')], help_text='Which level this role is meant to be assigned at (Company / Project / Topic).', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'authn_role',
                'ordering': ['company', 'scope', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope_object_type', models.CharField(choices=[('company', 'Company'), ('project', 'Project'), ('topic', 'Topic')], help_text='Which kind of object this assignment is scoped to (company / project / topic).', max_length=20)),
                ('scope_object_id', models.UUIDField(help_text='The id of that Company / Project / ChatTopic instance.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'authn_role_assignment',
            },
        ),
        migrations.CreateModel(
            name='RoleRight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'authn_role_right',
            },
        ),
    ]
