# Generated by Django 5.2.15 on 2026-08-01 03:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0001_initial'),
        ('nucleus', '0019_alter_channel_slug_alter_chattopic_slug_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Right',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text="Stable identifier, e.g. 'project.create'. Referenced by code everywhere, never by id.", max_length=100, unique=True)),
                ('object_type', models.CharField(choices=[('project', 'Project'), ('channel', 'Channel'), ('topic', 'Chat Topic'), ('session', 'Chat Session'), ('persona', 'Persona'), ('agent', 'AI Agent'), ('mcp_server', 'MCP Server'), ('ai_model', 'AI Model'), ('company', 'Company')], max_length=20)),
                ('scope', models.CharField(choices=[('company', 'Company'), ('project', 'Project'), ('topic', 'Topic')], help_text='Narrowest scope level this right can be granted at. See ScopeType docstring.', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'authn_right',
                'ordering': ['object_type', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text="The philosophy — why this role exists and what it's meant to represent.")),
                ('scope', models.CharField(choices=[('company', 'Company'), ('project', 'Project'), ('topic', 'Topic')], help_text='Which level this role is meant to be assigned at (Company / Project / Topic).', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Every role belongs to exactly one company. Custom roles are always company-specific.', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='nucleus.company')),
            ],
            options={
                'db_table': 'authn_role',
                'ordering': ['company', 'scope', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope_object_type', models.CharField(choices=[('company', 'Company'), ('project', 'Project'), ('topic', 'Topic')], help_text='Which kind of object this assignment is scoped to (company / project / topic).', max_length=20)),
                ('scope_object_id', models.UUIDField(help_text='The id of that Company / Project / ChatTopic instance.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_role_assignments', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='authn.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'authn_role_assignment',
            },
        ),
        migrations.CreateModel(
            name='RoleRight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('right', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_rights', to='authn.right')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_rights', to='authn.role')),
            ],
            options={
                'db_table': 'authn_role_right',
            },
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('company', 'name', 'scope'), name='uniq_role_name_per_company_scope'),
        ),
        migrations.AddIndex(
            model_name='roleassignment',
            index=models.Index(fields=['user', 'scope_object_type', 'scope_object_id'], name='authn_role__user_id_d557f3_idx'),
        ),
        migrations.AddIndex(
            model_name='roleassignment',
            index=models.Index(fields=['scope_object_type', 'scope_object_id'], name='authn_role__scope_o_aedfd0_idx'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(fields=('user', 'role', 'scope_object_type', 'scope_object_id'), name='uniq_user_role_scope'),
        ),
        migrations.AddConstraint(
            model_name='roleright',
            constraint=models.UniqueConstraint(fields=('role', 'right'), name='uniq_role_right'),
        ),
    ]
