# Generated by Django 5.2.15 on 2026-08-03 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authn', '0001_initial'),
        ('nucleus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='company',
            field=models.ForeignKey(help_text='Every role belongs to exactly one company. Custom roles are always company-specific.', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='nucleus.company'),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_role_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='authn.role'),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roleright',
            name='right',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_rights', to='authn.right'),
        ),
        migrations.AddField(
            model_name='roleright',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_rights', to='authn.role'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('company', 'name', 'scope'), name='uniq_role_name_per_company_scope'),
        ),
        migrations.AddIndex(
            model_name='roleassignment',
            index=models.Index(fields=['user', 'scope_object_type', 'scope_object_id'], name='authn_role__user_id_d557f3_idx'),
        ),
        migrations.AddIndex(
            model_name='roleassignment',
            index=models.Index(fields=['scope_object_type', 'scope_object_id'], name='authn_role__scope_o_aedfd0_idx'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(fields=('user', 'role', 'scope_object_type', 'scope_object_id'), name='uniq_user_role_scope'),
        ),
        migrations.AddConstraint(
            model_name='roleright',
            constraint=models.UniqueConstraint(fields=('role', 'right'), name='uniq_role_right'),
        ),
    ]
