# Generated by Django 5.2.17 on 2026-08-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0003_delete_devicesession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='right',
            name='object_type',
            field=models.CharField(choices=[('project', 'Project'), ('channel', 'Channel'), ('topic', 'Chat Topic'), ('session', 'Chat Session'), ('persona', 'Persona'), ('agent', 'AI Agent'), ('mcp_server', 'MCP Server'), ('ai_model', 'AI Model'), ('company', 'Company'), ('schedule', 'Persona Schedule')], max_length=20),
        ),
    ]
