"use client";

import { useEffect, useId, useState } from "react";

// LLMs constantly emit mermaid labels with characters the parser rejects —
// quote offending node labels before giving up.
function sanitizeMermaid(src: string): string {
  return src.replace(/([A-Za-z0-9_]+)\[([^\]"]*[()<>|&][^\]"]*)\]/g, (_, id, label) => `${id}["${label.replace(/"/g, "'")}"]`);
}

export function MermaidBlock({ source }: { source: string }) {
  const [svg, setSvg] = useState<string | null>(null);
  const [failed, setFailed] = useState(false);
  const reactId = useId();
  const renderId = `nx-mermaid-${reactId.replace(/[^a-zA-Z0-9]/g, "")}`;

  // Diagrams re-render when the theme flips — mermaid bakes colors into the
  // SVG at render time, so a dark diagram would stay dark on a light page.
  const [themeTick, setThemeTick] = useState(0);
  useEffect(() => {
    const bump = () => setThemeTick((t) => t + 1);
    const obs = new MutationObserver(bump);
    obs.observe(document.documentElement, { attributes: true, attributeFilter: ["data-theme"] });
    const mq = matchMedia("(prefers-color-scheme: dark)");
    mq.addEventListener("change", bump);
    return () => {
      obs.disconnect();
      mq.removeEventListener("change", bump);
    };
  }, []);

  useEffect(() => {
    let alive = true;
    (async () => {
      try {
        const { default: mermaid } = await import("mermaid");
        const dark = document.documentElement.dataset.theme === "dark" ||
          (!document.documentElement.dataset.theme && matchMedia("(prefers-color-scheme: dark)").matches);
        mermaid.initialize({ startOnLoad: false, securityLevel: "strict", theme: dark ? "dark" : "neutral" });
        let src = source;
        const ok = await mermaid.parse(src, { suppressErrors: true });
        if (!ok) {
          src = sanitizeMermaid(src);
          if (!(await mermaid.parse(src, { suppressErrors: true }))) throw new Error("unparseable");
        }
        const out = await mermaid.render(renderId, src);
        if (alive) setSvg(out.svg);
      } catch {
        if (alive) setFailed(true);
      }
    })();
    return () => {
      alive = false;
    };
  }, [source, themeTick, renderId]);

  if (failed) {
    return (
      <pre className="my-2 overflow-x-auto rounded-lg bg-surface2 p-3 font-mono text-[12px] text-ink2">{source}</pre>
    );
  }
  if (!svg) {
    return <div aria-hidden className="my-2 h-24 animate-pulse rounded-lg bg-surface2" />;
  }
  // Mermaid output is generated by the library from parsed source under
  // securityLevel: "strict" (labels are sanitized, no scripts/click handlers).
  return <div className="my-2 overflow-x-auto [&_svg]:max-w-full" dangerouslySetInnerHTML={{ __html: svg }} />;
}
