# Generated by Django 5.2.17 on 2026-08-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleus', '0002_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcpserver',
            name='secrets_encrypted',
            field=models.TextField(blank=True, help_text='Fernet-encrypted JSON dict of secret env vars. Do not set directly — use set_secrets().', null=True),
        ),
    ]
