# Generated by Django 5.2.17 on 2026-08-13 05:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        ('nucleus', '0003_mcpserver_secrets_encrypted'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('query_text', models.TextField(help_text='The prompt sent to the persona each time this schedule fires.')),
                ('label', models.CharField(blank=True, help_text='Optional short display name for this schedule. Falls back to a truncated query_text in the UI if left blank.', max_length=255)),
                ('schedule_kind', models.CharField(choices=[('interval', 'Interval (every N hours/minutes)'), ('crontab', 'Crontab (daily/weekly/monthly/specific weekdays)'), ('clocked', 'Clocked (one-time, a single specific date)')], db_index=True, max_length=20)),
                ('interval_every', models.PositiveIntegerField(blank=True, help_text="e.g. 1 for 'every 1 hour'. Only used when schedule_kind=interval.", null=True)),
                ('interval_period', models.CharField(blank=True, help_text="django_celery_beat.IntervalSchedule.PERIOD_CHOICES value, e.g. 'hours', 'minutes'. Only used when schedule_kind=interval.", max_length=20, null=True)),
                ('crontab_minute', models.CharField(blank=True, default='0', max_length=64)),
                ('crontab_hour', models.CharField(blank=True, default='*', max_length=64)),
                ('crontab_day_of_week', models.CharField(blank=True, default='*', max_length=64)),
                ('crontab_day_of_month', models.CharField(blank=True, default='*', max_length=64)),
                ('crontab_month_of_year', models.CharField(blank=True, default='*', max_length=64)),
                ('clocked_time', models.DateTimeField(blank=True, help_text='Exact one-time fire datetime (UTC). Only used when schedule_kind=clocked.', null=True)),
                ('timezone', models.CharField(default='UTC', help_text="IANA timezone name the schedule's times are interpreted in, e.g. 'America/Edmonton'.", max_length=64)),
                ('trigger_visible', models.BooleanField(default=True, help_text="If True, post a visible 'Scheduled: <query>' message before the persona replies, same as a normal @mention. If False, only the persona's reply appears.")),
                ('catch_up_missed', models.BooleanField(default=True, help_text='If True, a run missed while the server was down fires once on restart. If False, missed runs are skipped -- only the next regularly scheduled occurrence fires.')),
                ('is_paused', models.BooleanField(default=False, help_text="User-facing pause switch, distinct from is_active (soft delete). A paused schedule's periodic_task.enabled is kept in sync to False.")),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(choices=[('never_run', 'Never run'), ('success', 'Success'), ('failed', 'Failed')], default='never_run', max_length=20)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='nucleus.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('periodic_task', models.OneToOneField(blank=True, help_text='The PeriodicTask row whose schedule + enabled flag this row keeps in sync with. Created/updated/deleted by scheduling/services.py, never edited directly.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persona_schedule', to='django_celery_beat.periodictask')),
                ('persona', models.ForeignKey(help_text='Existing persona to run the query against -- old or new, no restriction.', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='nucleus.persona')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='nucleus.project')),
                ('topic', models.ForeignKey(help_text='The chat topic this scheduled query fires into.', on_delete=django.db.models.deletion.CASCADE, related_name='persona_schedules', to='nucleus.chattopic')),
            ],
            options={
                'db_table': 'workspace_persona_schedule',
                'indexes': [models.Index(fields=['company', 'project', 'topic'], name='workspace_p_company_1def32_idx'), models.Index(fields=['persona'], name='workspace_p_persona_841303_idx'), models.Index(fields=['is_active', 'is_paused'], name='workspace_p_is_acti_4f50a3_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('schedule_kind', 'interval'), _negated=True), models.Q(('interval_every__isnull', False), ('interval_period__isnull', False)), _connector='OR'), name='schedule_interval_requires_fields'), models.CheckConstraint(condition=models.Q(models.Q(('schedule_kind', 'clocked'), _negated=True), ('clocked_time__isnull', False), _connector='OR'), name='schedule_clocked_requires_time')],
            },
        ),
    ]
