# Generated by Django 5.2.17 on 2026-08-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleus', '0004_personaschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiagent',
            name='system_prompt',
        ),
        migrations.AddField(
            model_name='mcpserver',
            name='auth_type',
            field=models.CharField(choices=[('none', 'None'), ('static_secrets', 'Static Secrets'), ('oauth2', 'OAuth2')], db_index=True, default='static_secrets', max_length=20),
        ),
        migrations.AddField(
            model_name='mcpserver',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mcpserver',
            name='is_protected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mcpserver',
            name='oauth_config',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
