# Generated by Django 5.2.15 on 2026-07-24 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleus', '0017_m8_mcp_server_embedding_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatsession',
            new_name='workspace_c_user_id_d1b4c5_idx',
            old_name='workspace_chatsession_user_topic_idx',
        ),
        migrations.RenameIndex(
            model_name='chatsession',
            new_name='workspace_c_expires_692781_idx',
            old_name='workspace_chatsession_expires_at_idx',
        ),
    ]
