# Generated by Django 5.2.15 on 2026-08-01 03:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleus', '0018_rename_workspace_chatsession_user_topic_idx_workspace_c_user_id_d1b4c5_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='slug',
            field=models.SlugField(help_text='URL-safe identifier, unique per project. Auto-generated from name.', max_length=120),
        ),
        migrations.AlterField(
            model_name='chattopic',
            name='slug',
            field=models.SlugField(help_text='URL-safe identifier, unique per channel. Auto-generated from title.', max_length=120),
        ),
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Users with access to this project. Role/status tracked on ProjectMember.', related_name='member_projects', through='nucleus.ProjectMember', through_fields=('project', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(help_text='URL-safe identifier, unique per company. Auto-generated from name.', max_length=120),
        ),
    ]
